// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var button, makeSong;
  makeSong = this.makeSong;
  button = document.createElement('button');
  button.textContent = 'Make Song';
  button.addEventListener('click', function () {
    var note, song;
    song = makeSong(10);
    for (var i$ = 0, length$ = song.length; i$ < length$; ++i$) {
      note = song[i$];
      printLine(note);
    }
  });
  document.body.appendChild(button);
}.call(this);

//# sourceMappingURL=../bar.map
